spring:
  application:
    name: backend
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:h2:mem:klepaas
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

app:
  version: 0.0.1-SNAPSHOT

cloud:
  ncp:
    credentials:
      access-key: ${NCP_ACCESS_KEY:your-access-key-here}
      secret-key: ${NCP_SECRET_KEY:your-secret-key-here}
    region: ap-northeast-2
    storage:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: k-le-paas-build-source
    api:
      base-url: https://nks.apigw.ntruss.com
